???????.application.name=storecrm

# MySQL Configuration
???????.datasource.url=jdbc:mysql://storecrm.cpwaw4uck92u.eu-north-1.rds.amazonaws.com:3306/storecrm
???????.datasource.username=admin
???????.datasource.password=Karina9339
???????.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA (Hibernate) Configuration
???????.jpa.hibernate.ddl-auto=update
???????.jpa.show-sql=true
???????.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Swagger/OpenAPI Configuration
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# Enable the second-level cache for Hibernate
???????.jpa.properties.hibernate.cache.use_second_level_cache=true
???????.jpa.properties.hibernate.cache.region.factory_class=org.hibernate.cache.ehcache.EhCacheRegionFactory

# Enable query cache for Hibernate
???????.jpa.properties.hibernate.cache.use_query_cache=true
???????.jpa.properties.hibernate.cache.use_structured_entries=true

# Path to Ehcache configuration file
???????.jpa.properties.net.sf.ehcache.configurationResourceName=ehcache.xml

# Enable logging of request parameters
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Show SQL queries
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate=DEBUG

# Format SQL queries for easier reading
???????.jpa.properties.hibernate.format_sql=true
???????.jpa.properties.hibernate.use_sql_comments=true

# Set root logging level
logging.level.root=INFO
